modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-3.0"

[[mods]]
modId = "bte"
version = "@version@"
displayName = "BML's Transit Expansion"
authors = "BML"
description = "A mod for the Minecraft Transit Railway mod and add somethings that mainly about platform"
logoFile = "icon.png"

[[dependencies.bte]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bte]]
modId = "minecraft"
mandatory = true
versionRange = "[@minecraft@]"
ordering = "NONE"
side = "BOTH"

[[dependencies.bte]]
modId = "mtr"
mandatory = true
versionRange = "[4.0.0,4.1)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bte]]
modId = "jsblock"
mandatory = true
versionRange = "[2.0.0,2.1)"
ordering = "AFTER"
side = "BOTH"

